aws s3 cp s3://podcastsdatabase/dataset/2 2/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/3 3/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/4 4/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/5 5/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/6 6/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/7 7/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/8 8/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/9 9/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/10 10/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/11 11/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/12 12/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/13 13/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/14 14/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/15 15/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/16 16/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/17 17/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/18 18/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/19 19/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/20 20/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/21 21/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/22 22/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/23 23/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/24 24/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/25 25/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/26 26/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/27 27/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/28 28/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/29 29/ --recursive
aws s3 cp s3://podcastsdatabase/dataset/30 30/ --recursive
